version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          command: chmod 777 ./test.py
      - run:    ./test.py
      - run:
          command: ./manage.py