version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    executor: python/default
    steps:
      - checkout
      - run:
          ./test.py
      - run:
          command: ./manage.py